# Inserts a blank line between shell prompts
add_newline = false

[character]
vicmd_symbol = '[V](green) '

# Git symbols
[git_status]
conflicted = '~$count '
ahead = '⇡$count '
behind = '⇣$count '
untracked = '?$count '
stashed = '*$count '
modified = '!$count '
staged = '+$count '
renamed = '»$count '
deleted = '-$count '
