# Inserts a blank line between shell prompts
add_newline = false

[character]
vicmd_symbol = '[V](green) '

[directory]
truncation_length = '5'
truncate_to_repo = false
format = '[$path]($style)[$lock_symbol]($lock_style) '
read_only = ''

[git_commit]
commit_hash_length = '7'
format = '[\[$hash\]]($style) [$tag]($style)'
tag_disabled = false

[git_status]
conflicted = '~$count'
ahead = '⇡$count'
behind = '⇣$count'
diverged = '⇕ $ahead$behind'
untracked = '?$count'
stashed = '*$count'
modified = '!$count'
staged = '+$count'
renamed = '»$count'
deleted = '-$count'
