#+title: Scripts
#+author: Shreeram Modi
#+options: toc:1
#+property: header-args:bash :noweb yes

This is a collection of scripts that I find useful, they are explained
below, mostly for my own documentation. All the scripts here are written
literately and compiled using =org-babel-tangle=, see [[#org-tangle][the
org-tangle script]].

All scripts include this to exit on error
#+name: error-handling
#+begin_src bash
set -e
#+end_src

* ~mutt2task~
This script creates a [[https://taskwarrior.org/][taskwarrior]] task
from an email in [[https://neomutt.org/][neomutt]]. The task format is
~Email from "<sender>" (<subject>)~, and it is tagged with the ~email~
tag.

This creates a temp file for the script to use for sed operations.
There's probably a cleaner way to do this that doesn't modify the
filesystem but alas I am lazy.

#+begin_src bash :tangle mutt2task :shebang "#!/usr/bin/env sh"
<<error-handling>>

export TEMP
TEMP="$(mktemp)"
#+end_src

This is the line that does all the heavy lifting. It first searches for
lines in the email starting with =Subject:= or =From:=, then passes them
on to sed. Here are all the sed operations explained in order:

1. Removes everything in the line up to and including =:=
2. Removes the email address by searching for an =@= symbol inside =<>=,
   which leaves just the sender's name in the =From:= field
3. Places everything in the second (subject) line inside parentheses
4. Prepends the first line (from) with "Email from"

Sed then passes the two lines to paste, which concatenates them using a
space as a delimiter, the one line is then echoed to the temp file which
was created earlier.

#+begin_src bash :tangle mutt2task :shebang "#!/usr/bin/env sh"
grep -E '^Subject: |^From: ' | sed 's/.*: //; s/ <.*@.*>//; 2s/\(.*\)/(\1)/; 1s/^/Email from /' | paste -d " " - - > "$TEMP"
#+end_src

Finally the contents of the temp file, just the task, are added to
taskwarrior with the email tag, and the temp file is removed.

#+begin_src bash :tangle mutt2task :shebang "#!/usr/bin/env sh"
task add +email "$(cat "$TEMP")"

rm "$TEMP"
#+end_src

* ~mutt2org~
This script is very similar to =mutt2task= but instead of taskwarrior it
converts an email into a task for org mode.

Since org mode tasks are stored in specific files the script needs to
identify the file to save the task to.

#+begin_src bash :tangle mutt2org :shebang "#!/usr/bin/env sh"
<<error-handling>>

export ORGFILE="$HOME/Dropbox/org/inbox.org"
export TEMP
TEMP="$(mktemp)"
#+end_src

This just reuses the =grep= and =sed= commands from =mutt2task= except
modified to apply better to org files.
#+begin_src bash :tangle mutt2org :shebang "#!/usr/bin/env sh"
grep -E '^Subject: |^From: ' | sed 's/.*: //; s/ <.*@.*>//; 2s/\(.*\)/(\1) :email:/; 1s/^/* TODO Email from /' | paste -d " " - - > "$TEMP"
#+end_src

The task should show up on the current day of the org agenda so it is
scheduled for today using =date= with the appropriate format for org.
#+begin_src bash :tangle mutt2org :shebang "#!/usr/bin/env sh"
echo "SCHEDULED: <$(date +%Y-%m-%d)>" >> "$TEMP"
#+end_src

The specified org file should exist, if it doesn't then the script
throws an error.
#+begin_src bash :tangle mutt2org :shebang "#!/usr/bin/env sh"
if [ -e "$ORGFILE" ]
then
  cat "$TEMP" >> "$ORGFILE"
  rm "$TEMP"
  exit 0
else
  echo "Error \$ORGFILE does not exist!"
  rm "$TEMP"
  exit 1
fi
#+end_src

* ~org-tangle~
This script tangles org files from the command line, allowing you to
generate files without the need to open up emacs. It was taken from
[[https://orgmode.org/manual/Batch-Execution.html][the org manual]].

#+begin_src bash :tangle org-tangle :shebang "#!/usr/bin/env sh"
emacs -Q --batch --eval "
    (progn
      (require 'ob-tangle)
      (dolist (file command-line-args-left)
        (with-current-buffer (find-file-noselect file)
          (org-babel-tangle))))
  " "$@"
#+end_src

* ~colors~
This script changes my desktop and programs between dark and light mode.
Both use the respective schemes from
[[https://github.com/shrimpram/stella/][stella]], and the script just
toggles between the light and dark versions.

This defines the color function.

#+begin_src bash :tangle colors :shebang "#!/usr/bin/env sh"
<<error-handling>>

color () {
#+end_src

Most programs can be changed by switching the =current-theme= file in
their configuration directories. Rather than including the color scheme
rules in their config files, they source the =current-theme= file which
is changed between stella-dark and stella-light. Services
([[https://github.com/cmacrae/spacebar][spacebar]] and
[[https://github.com/koekeishiya/yabai/][yabai]]) need to be restarted
as well.

#+begin_src bash :tangle colors :shebang "#!/usr/bin/env sh"
# Kitty
cp "$HOME/.config/kitty/themes/stella-$COLOR.conf" "$HOME/.config/kitty/current-theme.conf"

# Spacebar
cp -a "$HOME/.config/spacebar/themes/stella-$COLOR" "$HOME/.config/spacebar/current-theme"
brew services restart spacebar

# Yabai
cp -a "$HOME/.config/yabai/themes/stella-$COLOR" "$HOME/.config/yabai/current-theme"
brew services restart yabai

# Zathura
cp -a "$HOME/.config/zathura/themes/stella-$COLOR" "$HOME/.config/zathura/current-theme"
#+end_src

For neovim the color scheme is set inside =init.lua=, and so sed is
used to change it between dark and light. However, the version of sed
existing on Mac systems is different than Linux systems so the commands
are slightly different. Sed on Mac requires the backup file extension to also
be passed as an argument, whereas sed on Linux does not.

#+begin_src bash :tangle colors :shebang "#!/usr/bin/env sh"
# Nvim
if [ "$(uname -s)" = "Darwin" ]; then
  sed -Ei '.bak' "s/stella-$OLD_COLOR/stella-$COLOR/" "$HOME/dotfiles/nvim/.config/nvim/init.lua"
  rm "$HOME/dotfiles/nvim/.config/nvim/init.lua.bak"
elif [ "$(uname -s)" = "Linux" ]; then
  sed -Ei "s/stella-$OLD_COLOR/stella-$COLOR/" "$HOME/dotfiles/nvim/.config/nvim/init.lua"
fi
#+end_src

Applescript lets us change the wallpaper, however the main drawback is
that it only allows us to change the wallpaper of the current desktop.

#+begin_src bash :tangle colors :shebang "#!/usr/bin/env sh"
# Wallpaper
if [ "$(uname -s)" = "Darwin" ]; then
  osascript -e "tell application \"Finder\" to set desktop picture to POSIX file \"$HOME/Pictures/celeste-$COLOR.png\""
fi
#+end_src

Applescript also lets us change between the system's dark and light
modes, which also change apps that allow the colorscheme to be set to
match the system.

#+begin_src bash :tangle colors :shebang "#!/usr/bin/env sh"
# Dark/Light Mode
if [ "$COLOR" = "dark" ]; then
  osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to true'
elif [ "$COLOR" = "light" ]; then
  osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to false'
fi
}
#+end_src

Rather than having different functions for changing to light and dark,
the script just reads the argument following ~color~. Then it sets the
~COLOR~ and ~OLD_COLOR~ variables based on what the user has typed and
changes the colors accordingly since all the parts of the script use
those variables instead of hardcoded light/dark.

#+begin_src bash :tangle colors :shebang "#!/usr/bin/env sh"
if [ "$1" = "light" ]; then
  COLOR="light"
  OLD_COLOR="dark"
  color
elif [ "$1" = "dark" ]; then
  COLOR="dark"
  OLD_COLOR="light"
  color
fi
#+end_src

* ~spot~
This script is a helper script for
[[https://github.com/Rigellute/spotify-tui][spotify-tui]] that provides
two functions, displaying the currently playing song as a notification
through
[[https://github.com/julienXX/terminal-notifier][terminal-notifier]],
and fetching the song's lyrics through [[https://genius.com/][Genius]]
and displaying them in ~$PAGER~.

This is just usage information for the script.

#+begin_src bash :tangle spot :shebang "#!/usr/bin/env bash"
<<error-handling>>

usage="$(basename "$0") [nowplaying lyrics] -- support program to interact with spotify-tui

  nowplaying (np)       show the currently playing song as a terminal-notifier notification
  lyrics (lr)           display the currently playing song's lyrics in \$PAGER
"
#+end_src

To access the Spotify API we need an OAuth token, which is generated
below. =Media/spt= should be a file with two lines, the first being a
Spotify client ID and the second being the corresponding Client Secret.
This is then encoded to be used with the Spotify API.

#+begin_src bash :tangle spot :shebang "#!/usr/bin/env bash"
enc="$(echo -n "$(pass show Media/spt | gsed -z 's/\n/:/')" | openssl base64 | tr -d '\n')"
#+end_src

This requests an access token from Spotify using the encoded ID and
Secret, the output is json so ~jq~ is used to parse just the token.

#+begin_src bash :tangle spot :shebang "#!/usr/bin/env bash"
token=$(curl -sX "POST" -H "Authorization: Basic $enc" -d grant_type=client_credentials https://accounts.spotify.com/api/token | jq '.access_token' | tr -d '"')
#+end_src

To interact with the Spotify API we need just the track id. However,
~spt~ returns the url of the currently playing track. So the track id is
parsed from the url using ~sed~.

#+begin_src bash :tangle spot :shebang "#!/usr/bin/env bash"
trackid=$(spt playback --share-track | sed 's/https:\/\/open.spotify.com\/track\///')
#+end_src

To get the thumbnail image we can use Spotify's oEmbed service, see
[[https://stackoverflow.com/a/18294883][this]] stack overflow comment
for more info. Using the track id, we're able to fetch information about
the currently playing track from Spotify, then parse the thumbnail url
using [[https://github.com/stedolan/jq][jq]].

#+begin_src bash :tangle spot :shebang "#!/usr/bin/env bash"
trackimage=$(curl -s "https://open.spotify.com/oembed?url=spotify:track:$trackid" | jq '.thumbnail_url')
#+end_src

The curl command sends a get request to the tracks Spotify API using
~trackid~, and returns json output, which will be parsed later as
needed.

#+begin_src bash :tangle spot :shebang "#!/usr/bin/env bash"
trackinfo=$(curl -sX "GET" "https://api.spotify.com/v1/tracks/$trackid?market=ES" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $token")
#+end_src

The nowplaying function shows the currently playing song as a
notification using
[[https://github.com/julienXX/terminal-notifier][terminal-notifier]]. In
this version of the script, since we have the song information in json
format, we don't need hacky ~sed~ commands to get the name and can just
parse it from ~trackinfo~, seen at the end. The rest of the
~terminal-notifier~ command is filled using other information about the
song, ~trackimage~, and opens the album link when clicked.

#+begin_src bash :tangle spot :shebang "#!/usr/bin/env bash"
nowplaying () {
  terminal-notifier -title "Now Playing" -contentImage "$trackimage" -open "$(spt playback --share-album)" -message "$(echo "$trackinfo" | jq '.name')"
}
#+end_src


The lyrics function needs a Genius API token, which is also gotten
through pass and can be generated
[[https://genius.com/api-clients][here]].

~fullname~ is just the name of the track and the name of the artist
concatenated, which allows for a more accurate search using
[[https://github.com/johnwmillr/LyricsGenius][lyricsgenius]].

There's /probably/ a way to do this without requiring disk operations
but I'm also /fairly/ lazy, PR's welcome though ;). We create a temp
directory for ~lyricsgenius~ to save the song info json file to. Then jq
parses the lyrics from the json file. The sed operations are explained
in order, the ~r~ flag makes ~gsed~ use extended regular expressions,
which are needed for capturing parentheses.
1. Remove the double-quotes at the beginning of the first line
2. Remove the double-quotes at the end of the last line
3. Remove the numbers and "Embed" at the end of the last line
4. Replace all =\n= with the proper newline characters
5. Add two newlines after the song title

The temp directory is deleted and the output is piped to ~$PAGER~.

#+begin_src bash :tangle spot :shebang "#!/usr/bin/env bash"
lyrics () {
  export GENIUS_ACCESS_TOKEN
  GENIUS_ACCESS_TOKEN="$(pass show Media/Genius | tail -n1)";

  fullname="$(echo "$trackinfo" | jq '.name' | sed 's/^"//; s/"$//') $(echo "$trackinfo" | jq '.artists[] .name' | sed 's/^"//; s/"$//')"

  temp="$(mktemp -d)"
  cd "$temp"
  lyricsgenius --save song "$fullname"
  jq '.lyrics' lyrics*.json | gsed -r '1s/^"//; $s/"$//; $s/[0-9]*Embed$//; s/\\n/\n/g; 1s/(.*Lyrics)(.*)/\1\n\n\2/' | $PAGER
  rm -r "$temp"
}
#+end_src

This just determines which command to run based on the first argument
passed. If no/undefined arguments are passed it shows usage help.

#+begin_src bash :tangle spot :shebang "#!/usr/bin/env bash"
case "$1" in
  "np"|"nowplaying")
    nowplaying
    ;;
  "lr"|"lyrics")
    lyrics
    ;;
  *)
    echo "$usage" >&2
    ;;
esac
#+end_src
