[global]
username = "shrimpram"
password_cmd = "pass Media/Spotify | head -n1"
backend = "portaudio"
device_name = "spotifyd"
bitrate = 320
cache_path = "/Users/shreeram/.local/share/spotifyd"
volume_normalisation = true
normalisation_pregain = -10
